id = "phpx"
name = "PHPX"
version = "0.1.1"
schema_version = 1
authors = ["Sami Fouad"]
description = "PHPX language support (tree-sitter)"
repository = "https://github.com/samifouad/deka"
languages = ["languages/phpx"]
themes = []
icon_themes = []
capabilities = []

[lib]

[grammars.phpx_only]
repository = "https://github.com/samifouad/deka"
rev = "HEAD"
path = "tooling/tree-sitter-phpx"

[language_servers.phpx-lsp]
name = "PHPX Language Server"
language = "PHPX"

[context_servers]

[agent_servers]

[slash_commands]
