[package]
name = "deka-wasm-guest-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[features]
json = []

[dependencies]
quote = "1"
syn = { version = "2", features = ["full"] }
proc-macro2 = "1"
