[package]
name = "compile"
version = "0.1.0"
edition = "2024"

[dependencies]
core = { path = "../core" }
stdio = { path = "../stdio" }
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
flate2 = "1.0"

[dev-dependencies]
tempfile = "3.0"
