services:
  php-fpm:
    image: php:8.2-fpm-alpine
    volumes:
      - ./bench.php:/var/www/html/bench.php:ro
  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - php-fpm
    ports:
      - "8542:80"
    volumes:
      - ./bench.php:/var/www/html/bench.php:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
  apache:
    image: php:8.2-apache
    ports:
      - "8543:80"
    volumes:
      - ./bench.php:/var/www/html/bench.php:ro
