[package]
name = "modules_php"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
deno_core = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
